### ISSUE TITLE
Try/Catch needed

### ISSUE THREAD

**Issue by nsde** [SCDerox/FragCaesar#2]
Bei der Übersetzung gibt es einen Fehler, wenn ein Wort "Null"/Leer ist, hier der Fehler:

```
TypeError: Cannot read properties of undefined (reading '0')
    at /home/lix/Downloads/FragCaesar-master/index.js:38:23
    at Array.forEach (<anonymous>)
    at module.exports.getWordInformation (/home/lix/Downloads/FragCaesar-master/index.js:37:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /home/lix/Downloads/FragCaesar-master/test/test.js:6:17
```

**Comment by leonickl** [comment]
fixed it today with optional chaining
